# Generated by Django 4.0.2 on 2022-04-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
