# Generated by Django 4.0.2 on 2022-07-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='params',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
